export { default as logo } from './air-bnb-logo.png'
export { default as grid } from './hero-grid.png'
export { default as katie } from './katie-zaferes.png'
export { default as star } from './Star.png'
export { default as wedding } from './wedding-photography.png'
export { default as bike } from './mountain-bike.png'